### ISSUE TITLE
Research and spec caching service

### ISSUE THREAD

**Issue by oed** [uport-project/3box#338]
This includes
* Come up with the best possible architecture
* GraphQL endpoint
* Separate or integrated into pinning-server? (how tightly coupled?)

**Comment by oed** [comment]
Pasting my convo with Eric Juta:

---

Eric Juta [12:05]
the latter sounds interesting :slightly_smiling_face:
cool so  `getProfile(publicAddress: String)` would be the gql query signature?
`getProfile(publicAddress: String) {  id avatar, ...etc }`
so you want to build something like this
https://github.com/Intellicode/graphql-resolver-cache/blob/master/src/cache.js
src/cache.js

essentially you wrap you business logic function i.e. the function that calls 3box-js getProfile touching origin data
in a custom withCache decorator function
which potentially fetches from a clustered redis first or something
and that withCache(businessLogic) is your graphql resolver
for the getProfile query
https://www.apollographql.com/docs/graphql-tools/resolvers
apollographql.com
Resolvers | GraphQL Tools
Writing resolvers with graphql-tools
full tutorial is here
https://www.robinwieruch.de/graphql-apollo-server-tutorial/
robinwieruch.derobinwieruch.de
GraphQL Server Tutorial with Apollo Server and Express - RWieruch
Learn how to build a GraphQL server with Apollo Server and Express with authentication, authorization, pagination, subscription, database access, tests ...
https://www.robinwieruch.de/img/posts/graphql-apollo-server-tutorial/banner_640.jpg
definitely use apollo server 2
https://www.apollographql.com/docs/apollo-server/whats-new.html
apollographql.com
What's new? | Apollo Server
A quick rundown of big announcements in the Apollo Server ecosystem.
so you define a graphql schema spec
combine that with your hand written resolvers
add any decorators/middleware if you want like overall LRU cache or per resolver cache via resolver function decorators


oed [12:13]
Thanks, will look at this after my lunch :slightly_smiling_face:


Eric Juta [12:13]
https://www.apollographql.com/docs/apollo-server/whats-new.html#GraphQL-Playground
that snippet explains the structure of the graphql server in only a few lines :slightly_smiling_face:
apollographql.com
What's new? | Apollo Server
A quick rundown of big announcements in the Apollo Server ecosystem.
cool, enjoy!


oed [13:27]
Ok, sweet. This is very helpful!
So basically our caching system would work something like this:
1. we have a caching server that detects when a user is opening a db and starts to cache the data of that db. It provides a gql api using apollo server.
2. getProfile always checks the caching server first, if no data is available on there it fetches the data from the orbitdb for the user.
3. we can also provide a way to do getProfile for multiple users at once


Eric Juta [13:45]
not too sure about the implementation of 1
but yeah 2 and 3 can be done via what i've said above
for sure :slightly_smiling_face:
so the graphql server makes the getProfile request for the user via 3box-js if it's not in the cache first


oed [13:47]
hm, how would the graphql server know if the cache it has is out of date? Do we just have a timeout?


Eric Juta [13:48]
mm could make a .setProfile on 3box
and use a graphql mutation there
also string match on public.set(keyToMatch)
to use graphql mutation too


oed [13:49]
hm, maybe
Does the graphql server store the cache in memory, or in a regular db?
usually


Eric Juta [13:51]
mm usually user defined
apollo has a SAAS which does query caching, analysis for you too i believe
hence i recommend apollo server cause it's compatible with their stuff


oed [13:52]
that makes sense. So maybe we start with in memory cache, and then go from there


Eric Juta [13:53]
yup!
yeah stereotypically people use the mongoose driver or a postgresql driver
but here you're using orbitdb/3box-js/ipfs which is pretty innovative!
https://github.com/ConsenSys/ethql
is a pretty good resource, was written in typescript + apollo server


oed [13:54]
nice
Still need to figure out the best architecture for this though. Might need to integrate this somehow with our pinning-server
the bad thing about orbitdb pinning is that you need to have instances running for each db


Eric Juta [13:55]
ah yikes yeah
yeah no idea if it makes sense to use the pinning server directly or 3box-js
also am i right in assuming you can use some sort of hidden method in 3box-js to generate an auth jwt?


oed [13:56]
hehe, that's my job to figure out :slightly_smiling_face:
auth for what?


Eric Juta [13:56]
not sure i think you mentioned there's a jwt signing method somewhere in the lib
probs could use that for private setters and getters in graphql over https
for dApps to use
(allows dApp serverside rendering)


oed [13:58]
yeah, we have that. But I think having a public gql lib over https is enough, then we can do rate limiting per domain
if dapps need serverside rendering


Eric Juta [13:58]
ah makes sense
yeah graphql allows a lot of polymorphism, gets interesting quick with a lot of microservices :slightly_smiling_face:
enjoy!


oed [13:59]
ty!

**Comment by michaelsena** [comment]
Related: https://github.com/uport-project/3box/issues/281

**Comment by oed** [comment]
Looking closer it seems like thegraph only deals with blockchain data, so might not be so interesting for now.

**Comment by michaelsena** [comment]
Yeah they’re used for querying on-chain data, but good to look at their patterns, so that when developers want to “get data about a user” they don’t have two radically different interfaces for on-chain and 3Box data. Maybe? cc @oed

**Comment by c-castillo** [comment]
# Caching service

## Rationale

If your application has a lot of public data that doesn’t change very frequently, and it’s important for it to load quickly, you’ll probably benefit from using a **CDN to cache** your API results. This can be particularly important for media or content companies like news sites and blogs.

A CDN will store your API result close to the edge of the network  (close to the region the user is in )  and deliver a cached result much faster than it would have required to do a full roundtrip to your actual server. As an added benefit, you get to save on server load since that query doesn’t actually hit your API.

## Alternatives to explore

- [x]  Apollo link & engine
- [ ]  Relay

This two libraries are the most widely implemented at this time.

- [ ]  FlacheQL

## Tool

Apollo is the most widely-used tool for this. They provide the building blocks to create a caching service on top of graphql.

To run a server, only two libraries are required: `graphql` and `apollo-server`

Apollo server exposes an API. In order to make it work:

- Create a schema, in which both `types` and `attributes` should be defined. In our case, our type should be `Profile` and the attributes, the profile fields.
    - [ ]  Create a Profile schema
- Connect to a data source. Apollo allows to write custom logic for data fetch as stated in (5). Two action points are derived from this
    - [ ]  Write data fetching logic
    - [ ]  Create an orbitDB data source
- So far, we are only defining a schema and fetching data for the database, but one more component is missing in order to translate graphQL queries into data: a resolver. It's similar to the controller in an MVC model.
    - [ ]  Create profile resolver.
- At this point the API is finished. If at some point we decided to expose the api just to authenticated users, please refer to (6) to enable authentication

## Information Sources

1. [https://blog.usejournal.com/caching-with-graphql-what-are-the-best-options-e161b0f20e59](https://blog.usejournal.com/caching-with-graphql-what-are-the-best-options-e161b0f20e59)
2. [https://www.apollographql.com/docs/engine/proxy/guides.html](https://www.apollographql.com/docs/engine/proxy/guides.html)
3. [https://blog.apollographql.com/caching-graphql-results-in-your-cdn-54299832b8e2](https://blog.apollographql.com/caching-graphql-results-in-your-cdn-54299832b8e2)
4. [https://philsturgeon.uk/api/2017/01/26/graphql-vs-rest-caching/](https://philsturgeon.uk/api/2017/01/26/graphql-vs-rest-caching/)
5. [https://www.apollographql.com/docs/tutorial/data-source.html](https://www.apollographql.com/docs/tutorial/data-source.html)
6. [https://www.apollographql.com/docs/tutorial/resolvers.html#authentication](https://www.apollographql.com/docs/tutorial/resolvers.html#authentication)

**Comment by oed** [comment]
This overview is really clear and well written, thanks @c-castillo! 
Point 2: We need to specify how the data fetching logic work. How can we fetch all the data in the beginning when we spin the service up? How can we make sure that the data is always up to date, i.e. make sure to update the cache when a user updates the public profile.

Both the fetching logic and the profile resolver would live on the same server right? 

Point 4: I think we can do authentication (and rate limiting) based only on origin right? This could potentially become a revenue model in the future.

So other than some more fleshing out of point 2 specifics I feel pretty confident in what you've described!

**Comment by c-castillo** [comment]
Thanks @oed.
I've addressed your comments and the spec is updated. Will move this to Review/Testing to gather more feedback.

**Comment by oed** [comment]
Let me see if I understand this correctly.
1. We write some custom data fetching logic. (I don't think we can extend `RESTDataSource` since we don't have a rest api)
2. When starting the caching service a function called something like `getAllProfiles` would be executed. (This would require the caching service to know all of the eth-addresses, or muport-dids of all users)
3. All profiles should now be cached an fetchable from the GraphQL api.

A bunch of questions here:
* How do we get all addresses/dids in 2? I guess we could just get them from the address-server?
* How is the cache invalidated when a user updates their profile?
* Can we automatically update the cache when a user updates their profile?

### A potential implementation
I think I've come up with a quite simple way to implement this that should be fairly simple.
Let's start with some updates to our existing services:
1. Add a new endpoint to the address-server: `getAllOdbAddresses`
2. Add a REST API to the pinning-server: `getProfile(odbAddress)`

These endpoints should only be accessible internally by our caching service.
Now the Apollo service can be implemented in a fairly standard way:

3. Create data fetching logic extending `RESTDataSource` which calls the pinning-server api (and likely also the address-server api)
4. We still need to think about how we do cache invalidation.

Hope this makes sense @c-castillo :)

**Comment by oed** [comment]
> Correct. Only if we enable a function to get all the profiles. If we want to bulk load the profiles we don't need to query the address server, only return the profiles with the orbitDB addresses provided.

Ah ok, I don't think we need to enable this use case. We should allow people to query for multiple addresses at once though.

> We can query the address server but long-term that won't probably scale. The address server can have their own cache (key-value in-memory database for example)

Right, can't we just make this graphql cache be the cache for both the orbit instances as well as the address-server?

> My first guess is a mutation should invalidate the cache, but if we are implementing our own cache, a rule for that can be written.

How would that work? Would the invalidation be done by the pinning server? If we implement our own, how does the rule work?

> Yes. The components of Apollo are flexible and they support common use cases like this. But, my guess is we will have to write these rules.

Ok, awesome!

**Comment by michaelsena** [comment]
@c-castillo would you mind breaking this research and spec into stories? TY!
